gitlabUrl: https://gitlab.example.com

hostAliases:
  - ip: "192.168.65.254"
    hostnames:
      - "gitlab.example.com"

rbac:
  create: true

runnerRegistrationToken: GR1348941eLym16V_xDcyBeUd-Hmj

securityContext:
  allowPrivilegeEscalation: true
  readOnlyRootFilesystem: false
  runAsNonRoot: false
  privileged: true

podSecurityContext:
  runAsUser: 0

certsSecretName: gitlab-cert-name

preEntrypointScript: |
  #!/bin/bash
  echo "Creating certificate file..."
  CERT_PATH="/usr/local/share/ca-certificates/gitlab.example.com.crt"
  touch $CERT_PATH
  cat > $CERT_PATH <<EOF
  -----BEGIN CERTIFICATE-----
  MIIC5DCCAcygAwIBAgIBADANBgkqhkiG9w0BAQsFADAdMRswGQYDVQQDDBJnaXRs
  YWIuZXhhbXBsZS5jb20wHhcNMjUwMTE1MDkyNTAyWhcNMjUwMjE0MDkyNTAyWjAd
  MRswGQYDVQQDDBJnaXRsYWIuZXhhbXBsZS5jb20wggEiMA0GCSqGSIb3DQEBAQUA
  A4IBDwAwggEKAoIBAQCF7H7C2c9rJhOkFT5znueq8lQg/EifFg70nTTRLe4D26Vp
  IBnEVnYWfBeeINyc8MqsOoDWMqsCz6r8sPsf/VqXJQGUUw8z8G9vxmL65IGQxoUW
  hjJsvRjoMfQBbnp5edQE1eyQiN4Je55Pkmq5iE37kxFeQGnZA5pNebnbVA1rsULx
  zH4CywtInn5qcZTtG9ZcPxGkmvZxIHU9iFb9ZU+4mtJrmZ5Yhk4hIetzJ72SXrYX
  qbeE3c3DhPlyOxt2N70wTwP5AMyhFONAWw6zRH+W9KHTacTVv5Gu3JhBmfBwjZlU
  MR2DHKkbTm05mQ6aYWnIvAMEOjlRafibn0Zs91NBAgMBAAGjLzAtMAwGA1UdEwEB
  /wQCMAAwHQYDVR0OBBYEFEGKh32N48k6BKIbjHqZox8rDG/wMA0GCSqGSIb3DQEB
  CwUAA4IBAQBgVcnhedekz8DEiYUNhbx/QeU8NaKhD+FskuY/WsSXqz/FNbIuaAzs
  1Mdj4zqlwEoABTH/8B42W5TCKgS4ySVnHERwZh8IFrcrLmmlRQINoUcJT4wzRu9l
  D/P+IS5x25NpK1hWgj9Ww5pyBBrt35jYiyr+x0eMChddeimcql59r+WqKwgFBbcv
  I6wSklUMRZ5TrSKx+AREgOvqDoPAbczb0ReuyAHpQ4UjePGrXN9rq1aUeLxChhiD
  djlzs6CFVTQig/LKlcg8RRGAlDU7Wyytroykv9YNJHVe/a+Hr/izxa6qRBFpwAP2
  IBqId+N/V1JVKVd2YpUUlM63YHPhoOVZ
  -----END CERTIFICATE-----
  EOF

  echo "Updating CA certificates..."
  update-ca-certificates
