apiVersion: v1
kind: ConfigMap
metadata:
  name: "order"
data:
  config.yml: |-
    server:
      port: "{{ .Values.config.server.port }}"

    postgres:
      masterDb:
        host: "{{ .Values.config.postgres.masterDb.host }}"
        port: "{{ .Values.config.postgres.masterDb.port }}"
        user: "{{ .Values.config.postgres.masterDb.user }}"
        password: "{{ .Values.config.postgres.masterDb.password }}"
        dbName: "{{ .Values.config.postgres.masterDb.db_name }}"
        autoCreateTables: {{ .Values.config.postgres.masterDb.auto_create_tables }}

      slaveDb:
        host: "{{ .Values.config.postgres.slaveDb.host }}"
        port: "{{ .Values.config.postgres.slaveDb.port }}"
        user: "{{ .Values.config.postgres.slaveDb.user }}"
        password: "{{ .Values.config.postgres.slaveDb.password }}"
        dbName: "{{ .Values.config.postgres.slaveDb.db_name }}"
        autoCreateTables: {{ .Values.config.postgres.slaveDb.auto_create_tables }}
