apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "order-tracking-system.fullname" . }}
  labels:
    {{- include "order-tracking-system.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
              subPath: config.yml
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "order-tracking-system.fullname" . }}-config
