apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "order-tracking-system.fullname" . }}
  labels:
    {{- include "order-tracking-system.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /v1/liveness
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /v1/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 15
          startupProbe:
            httpGet:
              path: /v1/startup
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
              subPath: config.yml
      volumes:
        - name: config-volume
          configMap:
            name: "order"
