replicaCount: 1

image:
    repository: calgor/order
    pullPolicy: Always
    tag: "v1.1"

config:
  server:
    port: "8080"

  postgres:
    masterDb:
      host: "my-release-postgresql-primary"
      port: "5432"
      user: "admin"
      password: "admin_password"
      db_name: "mydatabase"
      auto_create_tables: true

    slaveDb:
      host: "my-release-postgresql-read"
      port: "5432"
      user: "repl_user"
      password: "MjROL085LE"
      db_name: "mydatabase"
      auto_create_tables: false
